PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

Select ?s ?message {
		# all nif:RFC5147String must have begin index
		?s a nif:RFC5147String .
		FILTER ( NOT EXISTS {?s nif:endIndex ?o  } )
		BIND (concat(str(?s), ": all nif:RFC5147String must have end index") AS ?message)
}