PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

Select ?s ?message {
		?s a nif:RFC5147String .
		?s nif:anchorOf ?anchorOf .
		?s nif:beginIndex ?beginIndex .
		?s nif:endIndex ?endIndex .
		?s nif:referenceContext [ nif:isString ?referenceString ]  .
		BIND (SUBSTR(?referenceContext, ?beginIndex , (?endIndex - ?beginIndex) ) AS ?test ) .
		FILTER (str(?test) != str(?anchorOf )) .
		BIND (concat(str(?s), ": nif:anchorOf must match the substring of nif:isString calculated with begin and end index") AS ?message)
}
