PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Select * { 
		# all nif:Context must have nif:isString
		?s a nif:Context .
		FILTER (NOT EXISTS {?s nif:isString ?o } )
}
