PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

Select ?s ?message {
		?s a nif:Context .
		?s nif:isString ?string . 
		?s nif:endIndex ?length .
		BIND ( xsd:nonNegativeInteger(strlen(?string)) as ?a)
		BIND ( xsd:nonNegativeInteger(?length) as ?b)
		#LET (?a := xsd:nonNegativeInteger(strlen(?string)) ) .
		#LET (?b := xsd:nonNegativeInteger(?length) ) .
		FILTER ( ?a != ?b  )

		BIND (concat(str(?s), ": for the context, the length of nif:isString (",str(?a), ") must equal nif:endIndex(",str(?b),")" ) AS ?message)

}
